# This is a basic workflow to help you get started with Actions

name: build_CI

# Controls when the action will run.
on:
    # Triggers the workflow on push or pull request events but only for the main branch
    push:
        branches: [ main, master, dev ]
    pull_request:
        branches: [ main, master, dev ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build_on_ubuntu:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            -   uses: actions/checkout@v2
            # Install Qt Environment
            -   name: Install Qt
                uses: jurplel/install-qt-action@v2
                with:
                    version: '5.15.2'
                    host: 'windows'
                    target: 'desktop'
                    arch: 'linux_gcc_64'
                    dir: '${{ github.workspace }}/Qt/'
                    install-deps: 'true'
                    set-env: 'true'
                    modules: 'qtcore qtgui qtwidget'
                    cached: 'false'
            # Runs a single command using the runners shell
            -   name: build project
                run: |
                    mkdir build && cd build
                    cmake ..
                    cmake --build . --target all

    build_on_windows:
        # The type of runner that the job will run on
        runs-on: windows-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            -   uses: actions/checkout@v2
            # Install Qt Environment
            -   name: Install Qt
                uses: jurplel/install-qt-action@v2
                with:
                    version: '5.15.2'
                    host: 'windows'
                    target: 'desktop'
                    arch: 'win64_msvc2019_64'
                    dir: '${{ github.workspace }}/Qt/'
                    install-deps: 'true'
                    set-env: 'true'
                    modules: 'qtcore qtgui qtwidget'
                    cached: 'false'
            # Runs a single command using the runners shell
            -   name: build project
                shell: cmd
                run: |
                    call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
                    md build && cd build
                    cmake .. -G"NMake Makefiles"
                    cmake --build . --target all
